# -*- coding: utf-8 -*-
"""Business_Optimization_Modeling_Problem_10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dCOqjWKnT35As8p4ipQLkQvnzQThA4ro
"""

from scipy.optimize import linprog
from numpy import inf, dot

# objective coefficient vector
c = [0.15, -0.70]

# inequality constraints in the form A_ub x <= b_ub ('<=' means 'less than or equal to' here)
A_ub = [[-0.5, 1], [1, -1]]  # It's called A_ub because we are assuming these are all upper bound constraints (any lower bound constraints should be multiplied by -1)
b_ub = [0, 400000]

# bounds on variables
bounds = [[0, 1000000], [0, inf]]

print(linprog(c, A_ub=A_ub, b_ub=b_ub, bounds=bounds))

